"""
app.py — Supply Chain Executive Dashboard
Reads from demo_output.json (generated by demo_output.py).
Run: streamlit run app.py
"""
import json
from pathlib import Path

import pandas as pd
import streamlit as st

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Supply Chain Executive Dashboard",
    page_icon="📦",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------

DATA_CSV   = Path("data/supply_chain_data.csv")
CACHE_JSON = Path("demo_output.json")

if not DATA_CSV.exists():
    st.error(
        "**Dataset not found** — `data/supply_chain_data.csv` is missing.\n\n"
        "Clone the repo and ensure the dataset is present before running the dashboard."
    )
    st.stop()

if not CACHE_JSON.exists():
    st.warning(
        "**No cached results found** — `demo_output.json` is missing.\n\n"
        "Run the pipeline first:\n```\npython demo_output.py\n```"
    )
    st.stop()

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------

with open(CACHE_JSON, encoding="utf-8") as f:
    data = json.load(f)

decisions            = data.get("decisions", [])
patterns             = data.get("patterns", [])
concentration_risks  = data.get("concentration_risks", [])
executive_summary    = data.get("executive_summary", "")

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

st.title("📦 Supply Chain Executive Dashboard")
st.caption("Powered by a 4-agent AI pipeline · Results cached from last pipeline run")

st.divider()

# ---------------------------------------------------------------------------
# Top section — Agent 4 Strategic Insights
# ---------------------------------------------------------------------------

st.subheader("🔍 Strategic Portfolio Insights  *(Agent 4)*")

if executive_summary:
    st.info(f"**Executive Summary** — {executive_summary}")

if concentration_risks:
    st.markdown("**Critical Warnings**")
    for risk in concentration_risks:
        st.error(f"⚠️ {risk}")

if patterns:
    st.markdown("**Cross-SKU Patterns**")
    for pattern in patterns:
        st.markdown(f"- {pattern}")

st.divider()

# ---------------------------------------------------------------------------
# Bottom section — Agent 3 Tactical Decisions
# ---------------------------------------------------------------------------

st.subheader("📋 Tactical Reorder Decisions  *(Agent 3)*")

if not decisions:
    st.info("No decisions found in demo_output.json.")
else:
    ACTION_EMOJI = {
        "URGENT_REORDER": "🔴 URGENT REORDER",
        "REORDER":        "🟡 REORDER",
        "MONITOR":        "🟢 MONITOR",
    }

    # Summary metrics
    counts = {"URGENT_REORDER": 0, "REORDER": 0, "MONITOR": 0}
    for d in decisions:
        counts[d["action"]] += 1

    col1, col2, col3 = st.columns(3)
    col1.metric("🔴 Urgent Reorder", counts["URGENT_REORDER"])
    col2.metric("🟡 Reorder",        counts["REORDER"])
    col3.metric("🟢 Monitor",        counts["MONITOR"])

    st.markdown("")

    # Decision table
    rows = []
    for d in decisions:
        rows.append({
            "SKU":               d["sku"],
            "Product Type":      d["product_type"].capitalize(),
            "Action":            ACTION_EMOJI.get(d["action"], d["action"]),
            "Supplier":          d["recommended_supplier"],
            "Order Qty":         d["order_quantity"],
            "Reason":            d["reason"],
        })

    df = pd.DataFrame(rows)
    st.dataframe(df, use_container_width=True, hide_index=True)

    # Expandable detail per SKU
    with st.expander("View rejected suppliers per SKU"):
        for d in decisions:
            rejected = ", ".join(d.get("rejected_suppliers", [])) or "—"
            st.markdown(f"**{d['sku']}** — rejected: {rejected}")
